app_default/urls.py
from django.urls import path
from . import views

app_name = 'app_default'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'), # path함수는 path(route, view, kwargs, name)인 형태로 호출하며 4개의 인수를 설명하면 route : 주소를 의미, view : route 인수로 접근했을 때 호출할 view, kwargs : view에 전달될 값들, name : route의 이름을 의미
    path('<int:pk>/', views.DetailView.as_view(), name='detail'), # <>의 의미는 변수를 의미한다. 이 부분에 해당하는 값을 뷰에 인자로 전달한다. views.detail에 questioni_id 인자로 해당 값이 들어간다.
    path('<int:pk>/result/', views.ResultsView.as_view(), name='result'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('app_default/', include('app_default.urls')), # include는 다른 ulrs.py 파일을 참조할 수 있도록 한다. 그러니까 URI에 /app_default 이후 uri는 app_default 폴더 안에 존재하는 urls.py에서 검색하여 응답해준다는 의미이다.
    path('bookmark/', include('bookmark.urls')),
    path('admin/', admin.site.urls),
    path('', include('photo.urls')),
    path('account/', include('accounts.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/urls.py
from django.db import models
from django.urls import path
from django.views.generic.detail import DetailView
from .views import *
from .models import Photo


app_name = 'photo'

urlpatterns = [
    path('', photo_list, name='photo'),
    path('detail/<int:pk>/', DetailView.as_view(model=Photo, template_name='photo/detail.html'), name='photo_detail'),
    path('upload/', PhotoUploadView.as_view(), name='photo_upload'),
    path('delete/<int:pk>', PhotoDeleteView.as_view(), name='photo_delete'),
    path('update/<int:pk>', PhotoUpdateView.as_view(), name='photo_update'),
]

app_default/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200) # ChaarField는 문자열 타입, max_length 인자는 제약 조건으로 최대길이를 의미한다.
    pub_date = models.DateTimeField('date published') # DateTimeField는 날짜와 시간 형태 타입 인자값인 'date published'의미는 사람이 읽기 쉬운 형태를 사용한다라는 의미이다.

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    
    was_published_recently.admin_order_field = 'pub_date' # 원칙적으로 임의의 메서드에 의한 값은 정렬이 불가능. 대신 다른 값을 기준으로 정렬할 수 있는데 이 기준 항목을 설정하는 항목
    was_published_recently.boolean = True # 값이 불리언 값 형태인지 설정. True 설정하면 값 대신 아이콘이 나타난다.
    was_published_recently.short_description = 'Published recently?' # 항목의 헤더 이름을 설정


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE) # 왜래키 필드인 ForeignKey다. 인자값으로 참조할 객체(Table, Class)를 의미, 쉽게 설명하면 소속될 상대 객체를 의미한다. on_delete 인자는 상위 TB의 데이터를 삭제했을 시 해당 TB의 데이터 삭제에 대한 여부를 의미하는 인자다.
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

app_default/views.py
from django.db import models
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from .models import Choice, Question

# Create your views here.
class IndexView(generic.ListView):
    template_name = 'app_default/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published question."""
        return Question.objects.order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'app_default/detail.html'


class ResultsView(generic.DetailView):
    models = Question
    template_name = 'app_default/result.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'app_default/default.html', {
            'question' : question,
            'error_message' : "You didn't select a choice",
        })
    else:
        selected_choice.vote += 1
        selected_choice.save()

    return HttpResponseRedirect(reverse('app_default:result', args={question.id,}))

app_default/templates/app_default/detail.html
<h1>{{question.question_text}}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'app_default:vote' question.id %}" method="post">
  {% csrf_token %} <!-- CSRF 공격을 막기 위한 수단 중 하나. 서버로 들어온 요청이 사이트 내부에서 온것이 맞는지 확인하는 용도. -->
  {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"> <!-- forloop.counter는 Django templates 문법에서 제공하는 기능. 반복문의 반복 횟수를 출력해주는 기능. -->
    <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label>
  {% endfor %}
  <input type="submit" value="Vote" />
</form>

<ul>
    {% for choice in question.choice_set.all %}
      <li>{{ choice.choice_text }}</li>
    {% endfor %}
</ul>

app_default/templates/app_default/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'app_default/style.css' %}"

{% if latest_question_list %}
  <ul>
      {% for question in latest_question_list %}
        <li><a href="{% url 'app_default:detail' question.id %}">{{question.question_text}}</a></li>
      {% endfor %}
  </ul>
{% endif %}

app_default/templates/app_default/result.html
<h1>{{ question.question_text }}</h1>

<ul>
  {% for choice in question.choice_set.all %}
    <li> {{choice.choice_text}} -- {{ choice.votes }} vote{{ choice.votes|pluralize }} </li>
  {% endfor %}
</ul>

<a href="{% url 'app_default:detail' question.id %}">Vote again?</a>