config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('app_default/', include('app_default.urls')), # include는 다른 ulrs.py 파일을 참조할 수 있도록 한다. 그러니까 URI에 /app_default 이후 uri는 app_default 폴더 안에 존재하는 urls.py에서 검색하여 응답해준다는 의미이다.
    path('bookmark/', include('bookmark.urls')),
    path('admin/', admin.site.urls),
    path('', include('photo.urls')),
    path('account/', include('accounts.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/urls.py
from django.db import models
from django.urls import path
from django.views.generic.detail import DetailView
from .views import *
from .models import Photo


app_name = 'photo'

urlpatterns = [
    path('', photo_list, name='photo'),
    path('detail/<int:pk>/', DetailView.as_view(model=Photo, template_name='photo/detail.html'), name='photo_detail'),
    path('upload/', PhotoUploadView.as_view(), name='photo_upload'),
    path('delete/<int:pk>', PhotoDeleteView.as_view(), name='photo_delete'),
    path('update/<int:pk>', PhotoUpdateView.as_view(), name='photo_update'),
]

photo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Photo(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_photos')
    photo = models.ImageField(upload_to = 'photo/%Y/%m/%d', default='photos/no_image.png')
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True) # auto_now_add 인자는 Data가 insert 되었을 때 자동적으로 값을 설정한다.
    updated = models.DateTimeField(auto_now=True) # auto_now 인자는 Data가 Update되었을 때 자동적으로 값을 설정한다.


    class Meta:
        ordering = ['-updated'] # ordering 클래스 변수는 해당 모델의 객체들을 어떤 기준으로 정렬할 것인지 설정하는 옵션으로 -updated 옵션 값은 수정 시간의 내림차순으로 정렬한다.

    def __str__(self):
        return self.author.username + " " + self.created.strftime("%Y-%m-%d %H:%M:%S")

    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=[str(self.id)])

photo/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Photo

# Create your views here.
@login_required(redirect_field_name='', login_url='/account/login/')
def photo_list(request):
    photos = Photo.objects.all()
    print(request.GET.get("next"))
    print(photos)
    return render(request, 'photo/list.html', {'photos' : photos})


class PhotoUploadView(LoginRequiredMixin, CreateView):
    model = Photo
    fields = ['photo', 'text']
    template_name = 'photo/upload.html'

    login_url = '/account/login'
    redirect_field_name =''

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        if form.is_valid():
            form.instance.save()
            return redirect('/')
        else:
            return self.render_to_response({'form' : form})


class PhotoDeleteView(LoginRequiredMixin, DeleteView):
    model = Photo
    success_url = '/'

    login_url = '/account/login'
    redirect_field_name =''

    template_name = 'photo/delete.html'


class PhotoUpdateView(LoginRequiredMixin, UpdateView):
    model = Photo
    fields = ['photo', 'text']

    login_url = '/account/login'
    redirect_field_name =''
    
    template_name = 'photo/update.html'

photo/templates/photo/delete.html
{% extends 'photo_base.html' %}

{% block title %}- Delete{% endblock %}



{% block content %}
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default">
      <div class="alert alert-info">
        Do you wnat to delete {{object}}?
      </div>
      <form action="" method="post" enctype="multipart/form-data">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Delete" />
      </form>
    </div>
    <div class="col-md-2"></div>
  </div>
{% endblock %}

photo/templates/photo/detail.html
{% extends 'photo_base.html' %}

{% block title %}
  {{object.text | truncatechars:10}}
{% endblock %}



{% block content %}
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default">
      <p><img src="{{object.photo.url}}" style="width: 100%;"></p>
      <button type="button" class="btn btn-sx btn-info">{{ object.author.username }}</button>
      <p>{{ object.text | linebreaksbr }}</p>
      <a href="{% url 'photo:photo_delete' pk=object.id %}" class="btn btn-xs btn-outline-danger btn-sm float-right">Delete</a>
      <a href="{% url 'photo:photo_update' pk=object.id %}" class="btn btn-xs btn-outline-success btn-sm float-right">Update</a>
    </div>
    <div class="col-md-2"></div>
  </div>
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default">
      <div id="disqus_thread"></div>
    </div>
    <div class="col-md-2"></div>
  </div>
<script>
    /**
    *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
    *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */
    /*
    var disqus_config = function () {
    this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    */
    (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = 'https://prt-django-dstragram.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
{% endblock %}

photo/templates/photo/list.html
{% extends 'photo_base.html' %}

{% block title %}- List{% endblock %}



{% block content %}
  {% for post in photos %}
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-8 panel panel-default">
        <p><img src="{{post.photo.url}}" style="width: 100%;"></p>
        <button type="button" class="btn btn-sx btn-info">{{ post.author.username }}</button>
        <p>{{ post.text | linebreaksbr }}</p>
        <p class="text-right">
          <a href="{% url 'photo:photo_detail' pk=post.id %}" class="btn btn-xs btn-success">댓글달기</a>
        </p>
      </div>
      <div class="col-md-2"></div>
    </div>
  {% endfor %}
{% endblock %}

photo/templates/photo/update.html
{% extends 'photo_base.html' %}

{% block title %}- Update{% endblock %}



{% block content %}
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default">
      <form action="" method="post" enctype="multipart/form-data">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Update" />
      </form>
    </div>
    <div class="col-md-2"></div>
  </div>
{% endblock %}

photo/templates/photo/upload.html
{% extends 'photo_base.html' %}

{% block title %}- Upload{% endblock %}



{% block content %}
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default">
      <form action="" method="post" enctype="multipart/form-data">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Upload" />
      </form>
    </div>
    <div class="col-md-2"></div>
  </div>
{% endblock %}